apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inference
resources:
  - ../../base
configMapGenerator:
  - name: inference-mock-src
    files:
      - server.py
patches:
  - path: patch.yaml
